[package]
name = "oursh"
version = "0.1.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]

[dependencies]
nix = "*"

# Parsing

pest = "*"
pest_derive = "*"

# Terminal Control

# Option 1: http://man7.org/linux/man-pages/man3/termios.3.html
#termios = "*"
# Option 2: http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/
termion = "*"

