[package]
name = "oursh"
version = "0.2.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]

build = "build.rs"

[features]
default = ["history"]

cursor = []
history = ["cursor"]

[dependencies]
docopt = "*"
lalrpop-util = "0.16.0"
nix = "*"
pwd = "*"
regex = "*"
# Option 1: http://man7.org/linux/man-pages/man3/termios.3.html
#termios = "*"
# Option 2: http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/
termion = { git = "https://github.com/nixpulvis/termion", branch = "suspend-raw" }
utf8 = "*"

[build-dependencies]
lalrpop = "0.16.0"
