[package]
name = "oursh"
version = "0.3.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
description = "Modern, fast POSIX compatible shell"
license-file = "LICENSE"
documentation = "https://docs.rs/oursh"
homepage = "https://nixpulvis/oursh/oursh"
repository = "https://github.com/nixpulvis/oursh"

# Get with the times.
edition = "2018"

# Compile our parser grammars.
build = "build.rs"

[badges]
maintenance = { status = "dexperimental" }
travis-ci = { repository = "https://github.com/nixpulvis/oursh" }

[features]
default = ["raw", "history", "completion"]

shebang-block = []
completion    = []
history       = []
raw           = []

[dependencies]
docopt = "1.0"
lalrpop-util = "0.16.0"
nix = "0.11"
pwd = "1.3"
regex = "1.0"
# Option 1: http://man7.org/linux/man-pages/man3/termios.3.html
#termios = "*"
# Option 2: http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/
termion = { git = "https://github.com/redox-os/termion" }
trie-hugger = { path = "./trie_hugger" }
utf8 = "^0.0.2"

[build-dependencies]
lalrpop = "0.16.0"

[dev-dependencies]
chrono = "0.4"
assert_matches = "1.3"
criterion = "0.2"

[[bench]]
name = "shebang_block"
harness = false

[[bench]]
name = "compare"
harness = false

[[bench]]
name = "piped"
harness = false
