[package]
name = "oursh"
version = "0.2.0"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]

build = "build.rs"

[dependencies]
lalrpop-util = "0.16.0"
nix = "*"
regex = "*"
# Option 1: http://man7.org/linux/man-pages/man3/termios.3.html
#termios = "*"
# Option 2: http://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/
termion = "*"
utf8 = "*"

[build-dependencies]
lalrpop = "0.16.0"
